config/routes.rb
Rails.application.routes.draw do

  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  resources :programmes

  
  resources :projects
# get "/projects", to: "projects#index", as: 'projects'
# get "/projects/new", to: "projects#new", as: 'new_project'
# post "/projects", to: "projects#create", as: 'create_projects'
# get "/projects/:id/edit", to: "projects#edit", as: 'edit_project'
# get "/projects/:id", to: "projects#show", as: 'show_project'
# patch "/projects/:id", to: "projects#update", as: 'patch_project'
# put "/projects/:id", to: "projects#update", as: 'update_project'
# delete "/projects/:id", to: "projects#destroy", as: 'project'

  resources :tasks

  resources :todos

  
  resources :comments

  resources :users

  # Defines the root path route ("/")
  root "programmes#index"
end

app/models/programme.rb
class Programme < ApplicationRecord
   
   # adds methods to add and remove projects to an Programme, and much more.
   has_many :projects, dependent: :destroy

   # rolify
   resourcify
   has_many :users, through: :roles, class_name: 'User', source: :users
   has_many :creators, -> { where(roles: {name: :creator}) }, through: :roles, class_name: 'User', source: :users

   has_many :comments, as: :commentable

   # ensure all Programmes have a title
   validates :title, presence: true

   
end

app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController

   allow_unauthenticated_access only: %i[ index show ]

   before_action :set_programme, only: %i[ show edit update destroy ]

   def index

      # to do : Current model is not being populated..?
      flash[:notice] = Current.user
      @programmes = Programme.all
   end

   def show
      # @programme is retrieved by set_programme
      @projects = @programme.projects
      @comments = @programme.comments

      # future : review and use example - useful for deubugging?
      # render plain: @projects.inspect , status: 404

   end

   def new
      @programme = Programme.new
   end

   def create
      @programme = Programme.new(programme_params)
      if @programme.save

         # rolify
         Current.user.add_role :creator, @programme

         # when redirect_to is given an Active Record object, Rails generates a path for that record's show action:
         redirect_to @programme
      else
         #  save, unsuccessful: re-render the form so the user can fix the invalid data - render :new - redirects to new action w/ @programme
         #  set HTTP status to (422) Unprocessable Entity to tell the browser this POST request failed and to handle it accordingly.
         render :new, status: :unprocessable_entity
      end
    end
  
    def edit
    end
  
    def update
      if @programme.update(programme_params)
         redirect_to @programme
      else
         flash[:notice] = "The programme failed to update " + @programme.inspect
         render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @programme.destroy
      redirect_to programmes_path
    end

    private

      def set_programme
         @programme = Programme.find(params[:id])
      end

      # permitted parameters
      def programme_params
         params.expect(programme: [ :title, :tagline ])
      end


end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/programmes/_form.html.erb
<%= form_with model: programme, class: "flex_cols" do |form| %>

   <div class="form_row">
      <%= form.label :title %>
     <%= form.text_field :title, onkeydown: "HelperJS.enable_btn('submit_new_btn')" %>
   </div>

   <div class="form_row">
      <%= form.label "Tagline" %>
      <%= form.text_area :tagline, rows: 3 %>
   </div>
 
   <div class="flex align_end">
      <%= form.submit id: "submit_new_btn" , class: "inactive_btn" %>
      <%= link_to "Cancel", programme, class:"action_link " %>
   </div>
   
 <% end %>
 

app/views/programmes/create.html.erb
<h1>Programmes#create</h1>
<p>Find me in app/views/programmes/create.html.erb</p>

app/views/programmes/destroy.html.erb
<h1>Programmes#destroy</h1>
<p>Find me in app/views/programmes/destroy.html.erb</p>

app/views/programmes/edit.html.erb
<h1>Edit programme</h1>

<%= render "form", programme: @programme %>

app/views/programmes/index.html.erb
<section>

   <% # artifact bar %>
   <section class="artifact_bar">
      <div>
         <h4 class="light_grey_text">Home</h4>
         <h1>WayStation</h1>
      </div>
   </section>

   
   <% 
   # artifact index list 
   # we can't next .each do w/out breaking link_to structure, so we don't inc. links to users in these line items
   %>
   <section>
      <h3 class="grey_text">Programmes</h3>
      <ul class="in_page_artifacts_list">
         <% @programmes.each do |programme| %>
            <%= link_to programme do %>
               <li>
                  <div><!-- checkbox placeholder --></div>
                  <%= programme.title %>
                  <% if(programme.tagline.nil? || programme.tagline == "") then  %>
                     <span>&nbsp;</span>
                  <% else %>
                     <span><%=programme.tagline%></span>
                  <% end %>
                  <%= programme.created_at.strftime("%a %-d %b %Y %H:%M") %>
                  
                  <% # to do : tidy display - but we can't do a ''.each do' here - it messes w/ containing ''.each do' %>
                  <% if(programme.creators.length > 0) then %>
                     <div> 
                        <%= programme.creators.distinct.pluck(:name) %>
                     </div>
                  <% end %>
                  <% if(programme.users.length > 0) then %>
                     <div><%= programme.users.distinct.pluck(:name) %></div>
                  <% end %>

               </li>
            <% end %>
         <% end %>
      </ul>
      <div class="flex align_end">
         <%= link_to "New programme", new_programme_path, class: "action_link" if authenticated? %>
      </div>
   </section>


</section>

app/views/programmes/new.html.erb
<h1>New programme</h1>

<section>
   <%= render "form", programme: @programme %>
</section>

app/views/programmes/show.html.erb
<section>

   <% # artifact bar %>
   <section class="artifact_bar">
      <div>
         <%= link_to programmes_path, class: "p_0.25 m_0 no_decor inline_block hover_highlight" do %>
            <h4><span class="light_grey_text">Programmes</span></h4>
         <% end %>
         <h1><span class="light_grey_text">Programme</span> <%= @programme.title %></h1>

         <% # artifact tagline %>
         <div class="artifact_tagline"><%= @programme.tagline%></div>
      </div>
   </section>
  


   <!--<%= link_to "New project", new_project_path(programme_id:@programme.id) if authenticated? %>-->
   
   
   <% # artifact childrens list %>
   <section>
      <h3 class="grey_text">Projects</h3>
      <ul class="in_page_artifacts_list">
         <% @projects.each do |project| %>

            <%= link_to project do %>
               <li>
                  <div><!-- checkbox placeholder --></div>
                  <%= project.title %>
                  <% if(project.tagline.nil?) then  %>
                     <span>&nbsp;</span>
                  <% else %>
                     <span><%=project.tagline%></span>
                  <% end %>
                  <%= project.created_at.strftime("%a %-d %b %Y %H:%M") %>

                  <% if(project.creators.length > 0) then %>
                     <ul> 
                        <% project.creators.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>
                  <% if(project.users.length > 0) then %>
                     <ul class="flex flex_col"> 
                        <% project.users.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>

               </li>
            <% end %>
         
         <% end %>
      </ul>
      <div class="flex align_end">
         <%= link_to "New project", new_project_path(programme_id:@programme.id), class: "action_link"  if authenticated? %>
      </div>
   </section>


   <% # artifact ctrls %>
   <section class="flex align_end">
      <%= button_to(
            "Delete", @programme, 
            method: :delete, 
            class:"action_link" , 
            data: { turbo_confirm: "Are you sure you want to delete this entire programme?" }
         )
      %>
      <%= link_to "Edit", edit_programme_path(@programme) , class: "action_link" if authenticated? %>
   </section>
   <section>
      <%= link_to "All Programmes", programmes_path %>
   </section>

   
   <% # artifact assoc. users %>
   <% # to do : shared partial? %>
   <section>
      <h3>creators</h3>
      <% if(@programme.creators.length > 0) then %>
         <div> 
            <% @programme.creators.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>
         </div>
      <% end %>
      <h3>users</h3>
      <% if(@programme.users.length > 0) then %>
            <% @programme.users.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>         
         </div>
      <% end %>
   <section>


   <% # artifact comments %>
   <!% # we need to inc. 'partial' keyword to get the locals to work here.. %>
   <%= render partial: '/shared/comments', locals: { commentable_id: @programme.id, commentable_type: 'Programme'}  %>

</section>

app/views/programmes/update.html.erb
<h1>Programmes#update</h1>
<p>Find me in app/views/programmes/update.html.erb</p>