config/routes.rb
Rails.application.routes.draw do

  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  resources :programmes

  
  resources :projects
# get "/projects", to: "projects#index", as: 'projects'
# get "/projects/new", to: "projects#new", as: 'new_project'
# post "/projects", to: "projects#create", as: 'create_projects'
# get "/projects/:id/edit", to: "projects#edit", as: 'edit_project'
# get "/projects/:id", to: "projects#show", as: 'show_project'
# patch "/projects/:id", to: "projects#update", as: 'patch_project'
# put "/projects/:id", to: "projects#update", as: 'update_project'
# delete "/projects/:id", to: "projects#destroy", as: 'project'

  resources :tasks

  resources :todos

  
  resources :comments

  resources :users

  # Defines the root path route ("/")
  root "programmes#index"
end

app/models/task.rb
class Task < ApplicationRecord
   
   # adds methods to add and remove projects to an Programme, and much more.
   has_many :todos, dependent: :destroy
   
   belongs_to :project
   
   # rolify
   resourcify
   has_many :users, through: :roles, class_name: 'User', source: :users
   has_many :creators, -> { where(roles: {name: :creator}) }, through: :roles, class_name: 'User', source: :users

   has_many :comments, as: :commentable

   # ensure all Tasks have a title
   validates :title, presence: true


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

   allow_unauthenticated_access only: %i[ index show ]
   
   before_action :set_task, only: %i[ show edit update destroy ]


   def index

      @projects = Project.all
      @tasks = Task.all

      @augmented_tasks = []
      the_augmented_tasks = []

      # create list augmented w/ project.title
      @tasks.each do |task|
         my_project = Project.find(task.project_id)
         augmented_task = [task,my_project]
         the_augmented_tasks.push(augmented_task)
      end

      # sort by project and task title
      @augmented_tasks = the_augmented_tasks.sort_by { |task, project| [project.title, task.title] }
   end

   def show
      # @task is retrieved by set_task
      @project = @task.project
      @todos = @task.todos
      @comments = @task.comments
   end

   def new
      @task = Task.new
      @project_id = params[:project_id]
      @project = Project.find(@project_id)
      @programme = Programme.find(@project.programme_id)
   end

   def create

      # new task
      @task = Task.new(task_params)

      if @task.save

         # rolify
         Current.user.add_role :creator, @task
        
         redirect_to @task
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @project_id = params[:project_id]
      @project = Project.find(@project_id)
      @programme = Programme.find(@project.programme_id)
    end
  
    def update
      @project_id = params[:project_id]
      if @task.update(task_params)
         flash[:notice] = "we updated a Task"
        redirect_to @task
      else
         flash[:notice] = "The task failed to update " + @task.inspect
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @task.destroy
      redirect_to tasks_path
    end

    private
    
      def set_task
         @task = Task.find(params[:id])
      end

      def task_params
        params.expect(task: [ :title, :project_id, :tagline ])
      end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: task, class: "flex_cols" do |form| %>
   
   <div class="form_row">
     <%= form.label :title %>
     <%= form.text_field :title %>
   </div>

   <div class="form_row">
      <%= form.label "Tagline" %>
      <%= form.text_area :tagline, rows: 3 %>
   </div>
 
   <div class="form_row">
     <%= form.label :project_id %>
     <%= form.text_field :project_id, value:@project_id, readonly: true %>
   </div>

   <div class="flex align_end">

      <%= form.submit %>
      
      <% # data passed from view via locals Option : %> 
      <%= link_to "Cancel", cancel_dest, class:"action_link" %>

   </div>
   
 <% end %>
 

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">programme :  </span> 
      <span class="bold_text"> <%= link_to @programme.title, @programme, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
      <span class="grey_text">project :  </span> 
      <span class="bold_text"> <%= link_to @project.title, @project, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>Edit task</h1>
   <%= render partial: "form", locals: { task: @task, cancel_dest: task_path(@task) } %>
</section>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<% # to do : nav is not showing user.name correctly ? %>
<section>
   <ul class="all_artifacts_list">
      <% @augmented_tasks.each do |task,project| %>

         <%
         users_list = task.users
         %>
         <li>
            <%= link_to task.title, task %>
            <span class="parent_token">
               <span class="grey_text">project :  </span>
               <%= link_to project.title, project %>
            </span>
            
            <% if(task.creators.length > 0) then %>
               <div>creator: <%= task.creators.distinct.pluck(:name) %></div>
            <% end %>
            <% if(task.users.length > 0) then %>
               <div>users: <%= task.users.distinct.pluck(:name) %></div>
            <% end %>


         </li>
      <% end %>
   </ul>
</section>

app/views/tasks/new.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">programme :  </span> 
      <span class="bold_text"> <%= link_to @programme.title, @programme, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
      <span class="grey_text">project :  </span> 
      <span class="bold_text"> <%= link_to @project.title, @project, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>New task</h1>
   <section>
      <%= render partial: "form", locals: { task: @task, cancel_dest: project_path(@project_id) } %>
   </section>
</section>

app/views/tasks/show.html.erb
<section>

   <% # artifact bar %>
   <section class="artifact_bar">
      <div>
         <%= link_to project_path(@project), class: "p_0.25 m_0 no_decor inline_block hover_highlight" do %>
            <h4><span class="light_grey_text">Project</span> <%= @project.title %></h4>
         <% end %>
         <h1><span class="light_grey_text">Task</span> <%= @task.title %></h1>
         <!--h3><span class="light_grey_text">id</span> <%= @task.id %></h3-->
         
         <% # artifact tagline %>
         <div class="artifact_tagline"><%= @task.tagline%></div>

      </div>
   </section>

   <% 
   # artifact childrens list 
   # contains ctrls, so we limit Todo link to title only
   %>
   <section>
      <h3 class="grey_text">Todos</h3>
      <ul class="in_page_artifacts_list todos_list">

         <% @todos.each do |todo| %>

            <li class="contains_inline_form">

               <%= form_for todo, remote: true do |f| %>
                  <!-- don't let this influence container grid -->
                  <input type="hidden" name="authenticity_token" value={csrf} />

                  <% 
                     # set checkbox according to absence/presence of a done_at value
                     has_done_at = false
                     if(!todo.done_at.nil?) then 
                        has_done_at = true
                     end

                     # create btn id
                     btn_id = "todo_" + todo.id.to_s + "_update_btn"
                  %>

                  <div><%= f.checkbox :done_at, { checked: has_done_at, onclick: "HelperJS.enable_btn('#{btn_id}')" } %> </div>
                  <%= link_to todo do %>
                     <div><%= f.label :done_at, todo.title, class: "fit_content" %></div>
                  <% end %>

                  <% if(todo.creators.length > 0) then %>
                     <ul> 
                        <% todo.creators.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>
                  <% if(todo.users.length > 0) then %>
                     <ul class="flex flex_col"> 
                        <% todo.users.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>

                  <div><%= f.submit id: btn_id, class: "inactive_btn" %></div>      


            </li>
            <% end %>

         <% end %>
      </ul>
      <div class="flex align_end">
         <%= link_to "New todo", new_todo_path(task_id:@task.id) , class: "action_link "  if authenticated? %>
      </div>
   </section>

   <% # artifact ctrls %>
   <section class="flex align_end">
      <%= button_to(
            "Delete", 
            @task, 
            method: :delete, 
            class:"action_link" , 
            data: { turbo_confirm: "Are you sure you want to delete this Task and all child Todos?" } 
         )
      %>
      <%= link_to "Edit", edit_task_path(@task, project_id:@project.id), class: "action_link" if authenticated? %>
   </section>
   <section>
      <!-- alternative: <%= link_to "Back to parent project",  project_path(@project) %>-->
      <%= link_to "Back to parent project", @project %>
      <%= link_to "All Tasks", tasks_path %>
   </section>
   
   

   <% # artifact assoc. users %>
   <% # to do : shared partial? %>
   <section>
      <h3>creators</h3>
      <% if(@task.creators.length > 0) then %>
         <div> 
            <% @task.creators.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>
         </div>
      <% end %>
      <h3>users</h3>
      <% if(@task.users.length > 0) then %>
            <% @task.users.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>         
         </div>
      <% end %>
   <section>


   <% # artifact comments %>
   <!% # we need to inc. 'partial' keyword to get the locals to work here.. %>
   <%= render partial: '/shared/comments', locals: { commentable_id: @task.id, commentable_type: 'Task'}  %>


</section>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>