config/routes.rb
Rails.application.routes.draw do

  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  resources :programmes

  
  resources :projects
# get "/projects", to: "projects#index", as: 'projects'
# get "/projects/new", to: "projects#new", as: 'new_project'
# post "/projects", to: "projects#create", as: 'create_projects'
# get "/projects/:id/edit", to: "projects#edit", as: 'edit_project'
# get "/projects/:id", to: "projects#show", as: 'show_project'
# patch "/projects/:id", to: "projects#update", as: 'patch_project'
# put "/projects/:id", to: "projects#update", as: 'update_project'
# delete "/projects/:id", to: "projects#destroy", as: 'project'

  resources :tasks

  resources :todos

  
  resources :comments

  resources :users

  # Defines the root path route ("/")
  root "programmes#index"
end

app/models/project.rb
class Project < ApplicationRecord
   
   # adds methods to add and remove projects to an Programme, and much more.
   has_many :tasks, dependent: :destroy

   belongs_to :programme
   
   # rolify
   resourcify
   has_many :users, through: :roles, class_name: 'User', source: :users
   has_many :creators, -> { where(roles: {name: :creator}) }, through: :roles, class_name: 'User', source: :users

   has_many :comments, as: :commentable
   
   # ensure all Projects have a title
   validates :title, presence: true
   validates :programme_id, presence: true


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   
   allow_unauthenticated_access only: %i[ index show ]
   
   before_action :set_project, only: %i[ show edit update destroy ]


   def index

      @projects = Project.all
      @programmes = Programme.all

      @augmented_projects = []
      the_augmented_projects = []

      # create list augmented w/ project.title
      @projects.each do |project|
         my_programme = Programme.find(project.programme_id)
         augmented_project = [project,my_programme]
         the_augmented_projects.push(augmented_project)
      end

      # sort by project and project title
      @augmented_projects = the_augmented_projects.sort_by { |project, programme| [programme.title, project.title] }
   end

   def show
      # @project is retrieved by set_project
      @programme = @project.programme
      @tasks = @project.tasks
      @comments = @project.comments
   end

   def new
      @project = Project.new
      @programme_id = params[:programme_id]
      @programme = Programme.find(@programme_id)
   end

   def create
      @project = Project.new(project_params)
      if @project.save

         # rolify
         Current.user.add_role :creator, @project

        redirect_to @project
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @programme_id = params[:programme_id]
      @programme = Programme.find(@programme_id)
    end
  
    def update
      @programme_id = params[:programme_id]
      if @project.update(project_params)
        redirect_to @project
      else
         flash[:notice] = "The project failed to update " + @project.inspect
        render :edit, status: :unprocessable_entity
      end
    end
 
    def destroy
      @project.destroy
      redirect_to projects_path
    end

    private
    
      def set_project
         @project = Project.find(params[:id])
      end
      
      def project_params
         params.expect(project: [ :title, :programme_id, :tagline ])
      end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: project, class: "flex_cols" do |form| %>

   <div class="form_row">
     <%= form.label :title %>
     <%= form.text_field :title %>
   </div>

   <div class="form_row">
      <%= form.label "Tagline" %>
      <%= form.text_area :tagline, rows: 3 %>
   </div>
   
   <div class="form_row">
     <%= form.label :programme_id %>
     <%= form.text_field :programme_id, value:@programme_id, readonly: true %>
   </div>

   <div class="flex align_end">

      <%= form.submit %>

      <% # data passed from view via locals Option : %> 
      <%= link_to "Cancel", cancel_dest, class:"action_link" %>

   </div>

 <% end %>
 

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">programmme :  </span> 
      <span class="bold_text"> <%= link_to @programme.title, @programme, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>Edit project</h1>
   <% # Passing Data to form partial with locals Option : %>
   <%= render partial: "form", locals: { project: @project, cancel_dest: project_path(@project) } %>
</section>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<section>
   <ul class="all_artifacts_list">
      <% @augmented_projects.each do |project,programme| %>
         <li>
            <%= link_to project.title, project %>
            <span class="parent_token">
               <span class="grey_text">programme :  </span>
               <%= link_to programme.title, programme %>

               <% if(project.creators.length > 0) then %>
                  <div>creator: <%= project.creators.distinct.pluck(:name) %></div>
               <% end %>
               <% if(project.users.length > 0) then %>
                  <div>users: <%= project.users.distinct.pluck(:name) %></div>
               <% end %>

            </span>
         </li>
      <% end %>
   </ul>
</section>

app/views/projects/new.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">programme :  </span> 
      <span class="bold_text"> <%= link_to @programme.title, @programme, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>New project in projects</h1>

   <section>
      <% # Passing Data to form partial with locals Option : %>
      <%= render partial: "form", locals: { project: @project, cancel_dest: programme_path(@programme_id) } %>
   </section>
</section>

app/views/projects/show.html.erb
<section>

   <% # artifact bar %>
   <section class="artifact_bar">
      <!--h3 class="artfact_type light_grey_text">project</h3-->
      <div>
         <%= link_to programme_path(@programme), class: "p_0.25 m_0 no_decor inline_block hover_highlight" do %>
            <h4><span class="light_grey_text ">Programme</span> <%= @programme.title %></h4>
         <% end %>
         <h1><span class="light_grey_text">Project</span> <%= @project.title %></h1>
         <!--h3><span class="light_grey_text">id</span> <%= @project.id %></h3-->

         <% # artifact tagline %>
         <div class="artifact_tagline"><%= @project.tagline%></div>

      </div>
   </section>
   


   
   <% # artifact childrens list %>
   <section>
      <h3 class="grey_text">Tasks</h3>
      <ul class="in_page_artifacts_list">
         <% @tasks.each do |task| %>
            
            <%= link_to task do %>
               <li>
                  <div><!-- checkbox placeholder --></div>
                  <div><%= task.title %></div>
                  <% if(task.tagline.nil?) then  %>
                     <div>&nbsp;</div>
                  <% else %>
                     <div><%=task.tagline%></div>
                  <% end %>
                  <div><%= task.created_at.strftime("%a %-d %b %Y %H:%M") %></div>
                  
                  <% if(task.creators.length > 0) then %>
                     <ul> 
                        <% task.creators.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>
                  <% if(task.users.length > 0) then %>
                     <ul class="flex flex_col"> 
                        <% task.users.distinct.pluck(:name).each do |name| %>
                           <li>[<%=name%>]</li>
                        <% end %>
                     </ul>
                  <% end %>

               </li>
            <% end %>

         <% end %>
      </ul>
      <div class="flex align_end">
         <%= link_to "New task", new_task_path(project_id:@project.id) , class: "action_link"  if authenticated? %>
      </div>
   </section>


   <% # artifact ctrls %>
   <section class="flex align_end">   
      <!-- to do : currently, on delete a project, we are redirected to 'All Projects' page - should go to parent programme page : rollout all artifact deletions --> 
      <%= button_to(
            "Delete", 
            @project, 
            method: :delete, 
            class:"action_link" , 
            data: { turbo_confirm: "Are you sure you want to delete this entire project?" } 
         )
      %>
      <%= link_to "Edit", edit_project_path(@project, programme_id:@programme.id), class: "action_link" if authenticated? %>  
   </section>
   <section>
      <%= link_to "Back to parent programme",  programme_path(@programme) %>
      <%= link_to "All Projects", projects_path %>
   </section>
   

   <% # artifact assoc. users %>
   <% # to do : shared partial? %>
   <section>
      <h3>creators</h3>
      <% if(@project.creators.length > 0) then %>
         <div> 
            <% @project.creators.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>
         </div>
      <% end %>
      <h3>users</h3>
      <% if(@project.users.length > 0) then %>
            <% @project.users.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>         
         </div>
      <% end %>
   <section>


   <% # artifact comments %>
   <!% # we need to inc. 'partial' keyword to get the locals to work here.. %>
   <%= render partial: '/shared/comments', locals: { commentable_id: @project.id, commentable_type: 'Project'}  %>

</section>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>