config/routes.rb
Rails.application.routes.draw do

  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  resources :programmes

  
  resources :projects
# get "/projects", to: "projects#index", as: 'projects'
# get "/projects/new", to: "projects#new", as: 'new_project'
# post "/projects", to: "projects#create", as: 'create_projects'
# get "/projects/:id/edit", to: "projects#edit", as: 'edit_project'
# get "/projects/:id", to: "projects#show", as: 'show_project'
# patch "/projects/:id", to: "projects#update", as: 'patch_project'
# put "/projects/:id", to: "projects#update", as: 'update_project'
# delete "/projects/:id", to: "projects#destroy", as: 'project'

  resources :tasks

  resources :todos

  
  resources :comments

  resources :users

  # Defines the root path route ("/")
  root "programmes#index"
end

app/models/todo.rb
class Todo < ApplicationRecord

   belongs_to :task
   
   # rolify
   resourcify
   has_many :users, through: :roles, class_name: 'User', source: :users
   has_many :creators, -> { where(roles: {name: :creator}) }, through: :roles, class_name: 'User', source: :users

   has_many :comments, as: :commentable

   # ensure all Todos have a title
   validates :title, presence: true

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

   allow_unauthenticated_access only: %i[ index show ]

   before_action :set_todo, only: %i[ show edit update destroy ]

   def index
      @todos = Todo.all
      @tasks = Task.all

      @augmented_todos = []
      the_augmented_todos = []

      # create list augmented w/ project.title
      @todos.each do |todo|
         my_task = Task.find(todo.task_id)
         augmented_todo = [todo,my_task]
         the_augmented_todos.push(augmented_todo)
      end

      # sort by project and task title
      @augmented_todos = the_augmented_todos.sort_by { |todo, task| [task.title, todo.title] }
   end

   def show
      # @todo is retrieved by set_todo
      @task = @todo.task
      @project = @task.project
      @comments = @todo.comments
   end

   def new
      @todo = Todo.new
      @task_id = params[:task_id]
      @task = Task.find(@task_id)
      @project = Project.find(@task.project_id)
   end

   def create
      @todo = Todo.new(todo_params)
      if @todo.save

         # rolify
         Current.user.add_role :creator, @todo

        redirect_to @todo
      else
        render :new, status: :unprocessable_entity
      end
   end
  
   def edit
      @task_id = params[:task_id]
      @task = Task.find(@task_id)
      @project = Project.find(@task.project_id)
   end
  
    
   # update
   # we have two sources :
   # - full update from Todo update
   # - partial update from Tasks view
   def update

      # future : use to find definition of 'magic' methods
      # todo = Todo.first
      # todo.method(:comments).source_location
      # eg : mixin is a dynamic modulce called Post:: GeneratedAssociationMethods
      #  dynamically generated methods when you boot; models are then loaded
      
      test = ""

      @task_id = params[:task_id]
      now_done_at = ""
      rcvd_done_at = params[:todo][:done_at]
      if(rcvd_done_at == "1") then
         # note- we have to assign to params, todo_params is extracted from this at call to .update below
         params[:todo][:done_at] = Time.now.strftime("%Y-%m-%d %H:%M")
      end
      if(params) then flash[:notice] = "     todo_params: " + todo_params.to_s end
      
      if @todo.update(todo_params)
         redirect_to @todo
      else
         flash[:notice] = "The todo failed to update " + @todo.inspect
         render :edit, status: :unprocessable_entity
      end
   end
 
    def destroy
      @todo.destroy
      redirect_to todos_path
    end

    private
    
      def set_todo
         @todo = Todo.find(params[:id])
      end

      def todo_params
         params.expect(todo: [ :title, :task_id, :done_at])
      end


end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_comments.html.erb
<section>
   <ul>
      <% @comments.each do |comment| %>
         <li class="card">
            <div class="card_title_bar"><%= link_to comment.title, comment %></div>
            <div class="card_content"><%= comment.content %></div>
         </li>
      <% end %>
      <div class="flex align_end">
      <%= link_to "New comment", new_comment_path(commentable_id:@todo.id, commentable_type:"Todo") , class: "action_link"  if authenticated? %>
      </div>

   </ul>
</section>

app/views/todos/_form.html.erb
<%= form_with model: todo, class: "flex_cols" do |form| %>
   
   <div class="form_row">
     <%= form.label :title %>
     <%= form.text_field :title %>
   </div>
 
   <div>
     <%= form.label :task_id %>
     <%= form.text_field :task_id, value:@task_id, readonly: true %>
   </div>
 
   <div class="flex align_end">
   
      <%= form.submit %>

      <% # data passed from view via locals Option : %> 
      <%= link_to "Cancel", cancel_dest, class:"action_link" %>

   </div>

 <% end %>
 

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">project :  </span> 
      <span class="bold_text"> <%= link_to @project.title, @project, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
      <span class="grey_text">task :  </span> 
      <span class="bold_text"> <%= link_to @task.title, @task, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>Edit todo</h1>
   <%= render partial: "form", locals: { todo: @todo, cancel_dest: todo_path(@todo) } %>
</section>

app/views/todos/index.html.erb
<h1>All Todos</h1>

<section>
   <ul class="all_artifacts_list">
      <% @augmented_todos.each do |todo,task| %>
         <li>
            <%= link_to todo.title, todo %>
            <span class="parent_token">         
               <span class="grey_text">task :  </span>
               <%= link_to task.title, task %>
            </span>

            <% if(todo.creators.length > 0) then %>
               <div>creator: <%= todo.creators.distinct.pluck(:name) %></div>
            <% end %>
            <% if(todo.users.length > 0) then %>
               <div>users: <%= todo.users.distinct.pluck(:name) %></div>
            <% end %>

         </li>
      <% end %>
  </ul>
</section>

app/views/todos/new.html.erb
<section>
   <span class="parent_token m_1 ml_0">
      <span class="grey_text">project :  </span> 
      <span class="bold_text"> <%= link_to @project.title, @project, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
      <span class="grey_text">task :  </span> 
      <span class="bold_text"> <%= link_to @task.title, @task, class: "p_0.25 m_0 no_decor inline_block hover_highlight" %></span>
   </span>
</section>

<section>
   <h1>New todo</h1>

   <section>
      <%= render partial: "form", locals: { todo: @todo, cancel_dest: task_path(@task_id) } %>
   </section>
</section>

app/views/todos/show.html.erb
<section>

   <% # artifact bar %>
   <section class="artifact_bar">
      <div>
         <%= link_to project_path(@project), class: "p_0.25 m_0 no_decor inline_block hover_highlight" do %>
               <h5><span class="grey_text">Project</span> <%= @project.title %></h5>
         <% end %>
         <%= link_to task_path(@task), class: "p_0.25 m_0 no_decor inline_block hover_highlight" do %>
               <h4><span class="grey_text">Task</span> <%= @task.title %></h4>
         <% end %>
         <h1><%= @todo.title %></h1>
         <h3><span class="light_grey_text">id</span> <%= @todo.id %></h3>
         <% if (!@todo.done_at.nil?) then %>
         <h3><span class="grey_text">done_at</span> <%= @todo.done_at.strftime("%a %-d %b %Y %H:%M") %></h3>
         <% end %>
      </div>
   </section>

   <% # artifact ctrls %>
   <section class="flex align_end">        
      <%= button_to(
            "Delete", 
            @todo, 
            method: :delete, 
            class:"action_link" , 
            data: { turbo_confirm: "Are you sure you want to delete this Todo?" } 
         )
      %>
      <%= link_to "Edit", edit_todo_path(@todo, task_id:@task.id) , class: "action_link" if authenticated? %>
      <%= link_to "Cancel", @task, class: "action_link" %>
   </section>

   <section>
      <%= link_to "Back to parent task",  task_path(@task) %>
      <%= link_to "All Todos", todos_path %>
   </section>

   

   <% # artifact assoc. users %>
   <% # to do : shared partial? %>
   <section>
      <h3>creators</h3>
      <% if(@todo.creators.length > 0) then %>
         <div> 
            <% @todo.creators.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>
         </div>
      <% end %>
      <h3>users</h3>
      <% if(@todo.users.length > 0) then %>
            <% @todo.users.distinct.pluck(:id,:name).each do |id,name| %>
               <%= link_to name, user_path(id) %>
            <% end %>         
         </div>
      <% end %>
   <section>


   <% # artifact comments %>
   <!% # we need to inc. 'partial' keyword to get the locals to work here.. %>
   <%= render partial: '/shared/comments', locals: { commentable_id: @todo.id, commentable_type: 'Todo'}  %>
  

</section>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>